name: First Workflow
on: workflow_dispatch


jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye!"
      - name: Print multiple line commands
        run: | 
          echo first command
          echo second command
          

  
